July/urls.py
from django.conf.urls import url, include
from users.views import RegisterView, LoginView, LogoutView, PasswordView, RestPasswordView
from blog.views import *

from blog.feeds import RssSiteNewsFeed, AtomSiteNewsFeed
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import BlogSitemap

sitemaps = {
    'static': BlogSitemap,
}

urlpatterns = [
    # ========== Blog Home =========
    url(r'^$', ArticleListView.as_view(), name='index'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^article/(?P<article_url>.*)$', ArticleDetailView.as_view(), name='article'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # ========== User =========
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^password/$', PasswordView.as_view(), name='password'),
    url(r'^rest_password/$', RestPasswordView.as_view(), name='restpassword'),
    # ========== Admin =========
    url(r'^admin/', include('admin.urls', namespace='admin')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^rss\.xml$', RssSiteNewsFeed()),
    url(r'^atom\.xml$', AtomSiteNewsFeed()),
]

apps/admin/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from .views import *

urlpatterns = [
    url(r'^tag/$', TagView.as_view(), name='tag'),
    url(r'^link/$', LinkView.as_view(), name='link'),
    url(r'^users/$', UsersView.as_view(), name='users'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^setting/$', SettingView.as_view(), name='setting'),
    url(r'^upload/$', csrf_exempt(UploadView.as_view()), name='upload'),
    url(r'^categories/$', CategoriesView.as_view(), name='categories'),
    url(r'^article/add/$', ArticleAddView.as_view(), name='article-add'),
    url(r'^article/list/$', ArticleListView.as_view(), name='article-list'),
    url(r'^article/edit/$', ArticleEditView.as_view(), name='article-edit'),
    url(r'^article/body/$', ArticleBodyView.as_view(), name='article-body'),
    url(r'^message/os/$', MessageOSView.as_view(), name='message-os'),
    url(r'^message/comment/$', MessageCommentView.as_view(), name='message-comment'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]

apps/blog/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^comment/$', CommentsView.as_view(), name='comment'),
    url(r'^reply/$', ReplyView.as_view(), name='reply'),
]

apps/blog/models.py
from django.db import models

# Create your models here.

__all__ = [
    'Categories',
    'Article',
    'Link',
    'Tag',
    'Setting'
]


class Categories(models.Model):
    name = models.CharField(max_length=32, unique=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def categories_article_count(self):
        return self.article_set.all().count()


class Tag(models.Model):
    name = models.CharField(max_length=32, unique=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def tag_article_count(self):
        return self.article_set.all().count()


class Article(models.Model):
    STATUS_CHOICES = (
        ('0', '发布'),
        ('1', '存稿'),
    )

    title = models.CharField(max_length=32, unique=True)
    url = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    body = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    release_time = models.DateTimeField(default='1970-1-1 00:00:00')
    status = models.CharField(default=0, max_length=1, choices=STATUS_CHOICES)
    read = models.IntegerField(default=0)
    categories = models.ManyToManyField(Categories)
    tag = models.ManyToManyField(Tag)

    def get_categories(self):
        categories = ''
        for c in self.categories.all():
            categories += ',' + c.name
        return categories.strip(',')

    def get_tag(self):
        tag = ''
        for t in self.tag.all():
            tag += ',' + t.name
        return tag.strip(',')

    def get_comment_num(self):
        from users.models import Comment
        return Comment.objects.filter(article=self.id).count()

    def get_tags(self):
        return Tag.objects.filter(article=self.pk)


class Link(models.Model):
    name = models.CharField(max_length=32, unique=True)
    url = models.URLField(unique=True)
    description = models.CharField(max_length=255, default='此用户没有添加任何描述')
    add_time = models.DateTimeField(auto_now_add=True)


class Setting(models.Model):
    title = models.CharField(max_length=80)
    keywords = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    nickname = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to='%Y/%m', max_length=100)
    homedescription = models.CharField(max_length=150)
    recordinfo = models.CharField(max_length=100)
    statisticalcode = models.TextField()

apps/blog/forms.py
from django import forms


class CommentForm(forms.Form):
    url = forms.CharField(required=True)
    body = forms.CharField(required=True)


class ReplyForm(forms.Form):
    commentid = forms.CharField(required=True)
    body = forms.CharField(required=True)

apps/blog/views.py
from pure_pagination import Paginator, PageNotAnInteger
from django.shortcuts import render, HttpResponse
from django.views.generic import View
from django.db.models import Q
from .models import *
from .forms import *
from users.models import Comment, Reply
from utils.mixin_utils import LoginRequiredMixin

__all__ = [
    'ArticleListView',
    'ArticleDetailView',
    'CommentsView',
    'ReplyView',
    'AboutView'
]


# Create your views here.

class ArticleListView(View):
    def get(self, request):
        articles = Article.objects.filter(status=0).order_by('-created_time')
        search = request.GET.get('search')
        search_sm = request.GET.get('search_sm')
        if search:
            articles = articles.filter(Q(title__icontains=search) | Q(body__icontains=search))
        if search_sm:
            articles = articles.filter(Q(title__icontains=search_sm) | Q(body__icontains=search_sm))
        tag = request.GET.get('tag')
        categories = request.GET.get('category')
        if tag:
            T = Tag.objects.get(name=tag)
            articles = articles.filter(tag=T)
        if categories:
            C = Categories.objects.get(name=categories)
            articles = articles.filter(categories=C)
        page = request.GET.get('page', 1)
        paginator = Paginator(articles, 10, request=request)
        try:
            articles = paginator.page(page)
        except PageNotAnInteger:
            articles = paginator.page(1)
        comments = Comment.objects.all().order_by('-add_time')[:5]
        links = Link.objects.all()
        categories = Categories.objects.all()
        tags = Tag.objects.all()
        reads = Article.objects.all().order_by('-read')[:5]
        try:
            setting = Setting.objects.get(pk=1)
        except Setting.DoesNotExist:
            setting = None
        return render(request, 'index.html', {'articles': articles, 'comments': comments, 'links': links, 'categories': categories, 'tags': tags, 'reads': reads, 'setting': setting})


class ArticleDetailView(View):
    def get(self, request, article_url):
        try:
            article = Article.objects.get(url=article_url)
            article.read += 1
            article.save()
            comments = Comment.objects.filter(article=article).order_by('-add_time')
            url = 'https://' + request.get_host() + request.get_full_path()
            reads = Article.objects.all().order_by('-read')[:5]
            try:
                setting = Setting.objects.get(pk=1)
            except Setting.DoesNotExist:
                setting = None
            return render(request, 'article.html', {'article': article, 'comments': comments, 'url': url, 'reads': reads, 'setting': setting})
        except Article.DoesNotExist:
            return HttpResponse('404', status=404)


class CommentsView(LoginRequiredMixin, View):
    def post(self, request):
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            url = request.POST.get('url')
            body = request.POST.get('body')
            article = Article.objects.get(url=url)
            Comment.objects.create(article=article, user=request.user, body=body)
            return HttpResponse(status=200)
        else:
            return HttpResponse(comment_form.errors)


class ReplyView(LoginRequiredMixin, View):
    def post(self, request):
        reply_form = ReplyForm(request.POST)
        if reply_form.is_valid():
            commentid = request.POST.get('commentid')
            body = request.POST.get('body')
            comment = Comment.objects.get(pk=commentid)
            Reply.objects.create(user=request.user, comment=comment, body=body)
            return HttpResponse()
        else:
            return HttpResponse(reply_form.errors)


class AboutView(View):
    def get(self, request):
        article = Article.objects.all().last()
        article.read += 1
        article.save()
        comments = Comment.objects.filter(article=article).order_by('-add_time')
        url = 'https://' + request.get_host() + request.get_full_path()
        reads = Article.objects.all().order_by('-read')[:5]
        try:
            setting = Setting.objects.get(pk=1)
        except Setting.DoesNotExist:
            setting = None
        return render(request, 'article.html', {
            'article': article,
            'comments': comments,
            'url': url, 'reads': reads,
            'setting': setting})

apps/blog/templates/article.html
{% extends 'blog_base.html' %}
{% load staticfiles %}
{% block title %}
    <title>{{ article.title }}</title>
    <meta name="keywords" content={{ article.get_tag }}>
    <meta name="description" content=笔名安生，用博客记录成长!>
{% endblock %}
{% block custom_css %}
    <!-- Material design colors -->
    <link href="{% static 'blog/vendors/material-design-iconic-font/dist/css/material-design-iconic-font.min.css' %}" rel="stylesheet">

    <!-- CSS animations -->
    <link rel="stylesheet" href="{% static 'blog/vendors/animate.min.css' %}">

    <!-- Site -->
    <link rel="stylesheet" href="{% static 'blog/css/app_1.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/app_2.min.css' %}">
    <link rel="stylesheet" href="{% static 'editormd/css/editormd.preview.css' %}"/>
    <!-- Page Loader JS -->
    <script src="{% static 'blog/js/page-loader.min.js' %}" async></script>
    <style>
        .editormd-preview-container, .editormd-html-preview {
            padding: 0;
        }
    </style>
{% endblock %}
{% block container %}
    <section class="section">
        <div class="container">

            <article class="card blog">
                <div class="card__header">
                    <h1 style="font-size: 19px">{{ article.title }}</h1>

                    <small>
                        <span>发布时间：{{ article.created_time }}</span>
                        <span>浏览（{{ article.read }}）</span>
                        <span>评论（{{ article.get_comment_num }}）</span>
                        <span>分类：{{ article.get_categories }}</span>
                    </small>
                </div>

                <div class="card__body">
                    <div id="test-editormd-view2">
                        <textarea id="append-test" style="display:none;">
{{ article.body }}
                </textarea>
                    </div>
                </div>

                <div class="blog__tags">
                    {% for tag in article.get_tags %}
                        <a href="{% url 'index' %}?tag={{ tag.name }}" class="tags-list__item">#{{ tag.name }}</a>
                    {% endfor %}

                </div>

                <div class="blog__arthur">
                    <div class="blog__arthur-contents">
                        <h2>作者：<a href="https://blog.ansheng.me/">安生</a></h2>
                        <p>出处：<a href="{{ url }}">{{ url }}</a></p>
                        <p>本文章采用<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">知识共享署名-非商业性使用-相同方式共享4.0国际许可协议</a>进行许可。</p>
                    </div>
                </div>
            </article>

            <!-- Comment Lists -->
            <div class="card list-group blog-comment">
                <div class="list-group__header clearfix">
                    <span class="pull-left">{{ article.get_comment_num }}条迄今为止的评论</span>
                    <a href="#blog-comment" data-rmd-action="scroll-to" data-rmd-target="#blog-comment" data-rmd-offset="85" class="pull-right"><span class="hidden-xs">添加一个 </span>评论</a>
                </div>

                {% for comment in comments %}

                    <div class="list-group-item media">
                        <a href="" class="pull-left">
                            <img src="{{ MEDIA_URL }}{{ comment.user.image }}" class="list-group__img img-circle" width="50" height="50" alt="">
                        </a>
                        <div class="media-body list-group__text">
                            <strong>{{ comment.user.nick_name }}</strong>
                            <small>评论时间：{{ comment.add_time }}</small>
                            <p class="m-t-15">{{ comment.body }}</p>
                            <div class="actions actions--blog-comment dropdown">
                                <a href="" data-toggle="dropdown"><i class="zmdi zmdi-more-vert"></i></a>
                                <ul class="dropdown-menu dropdown-menu--icon pull-right">
                                    <li><a onclick="ShowReply({{ comment.id }},'reply')" data-rmd-action="blog-comment-open" style="cursor:pointer;"><i class="zmdi zmdi-mail-reply"></i> 回复</a></li>
                                </ul>
                            </div>
                        </div>


                        <!-- Sub comment list -->
                        {% for reply in comment.get_reply %}
                            <div class="list-group-item media">
                                <a href="" class="pull-left">
                                    <img src="{{ MEDIA_URL }}{{ reply.user.image }}" class="list-group__img img-circle" width="50" height="50" alt="">
                                </a>
                                <div class="media-body list-group__text">
                                    <strong>{{ reply.user.nick_name }}
                                        <small class="text-muted">@{{ reply.comment.user.nick_name }}</small>
                                    </strong>
                                    <small>回复时间：{{ reply.add_time }}</small>
                                    <p class="m-t-15">
                                        {{ reply.body }}
                                    </p>
                                    <!--
                                    <div class="actions actions--blog-comment dropdown">
                                        <a href="" data-toggle="dropdown"><i class="zmdi zmdi-more-vert"></i></a>
                                        <ul class="dropdown-menu dropdown-menu--icon pull-right">
                                            <li><a onclick="ShowReply({{ comment.id }},'replyreply',{{ reply.user.id }})" data-rmd-action="blog-comment-open" style="cursor:pointer;"><i class="zmdi zmdi-mail-reply"></i> 回复</a></li>
                                        </ul>
                                    </div>
                                    -->
                                </div>
                            </div>
                            <!-- End sub comment list -->
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
            <!-- Post a comment -->
            <div id="blog-comment" class="card card--dark" style="background-color: #3949AB">
                <div class="card__header">
                    <h2 id="ReplyCommentTips">发表你的评论</h2>
                    <small>在这里你可以畅所欲言~</small>
                </div>
                <div class="card__body">
                    <div class="form-group form-group--light form-group--float">
                        <textarea class="textarea-autoheight form-control" placeholder="写一些你要评论或回复的内容吧..." id="CommentBody"></textarea>
                        <i class="form-group__bar"></i>
                    </div>
                    {% if request.user.is_authenticated == True %}
                        <button id="ReplyComment" class="btn btn-default btn-sm m-t-15">添加评论</button>
                    {% else %}
                        <div class="load-more">
                            <a style="background-color: #fff;" href="{% url 'login' %}">登录后才可以评论哦~</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block custom_js %}
    <!-- Javascript -->

    <!-- jQuery -->
    <script src="{% static 'blog/vendors/jquery/dist/jquery.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'blog/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>

    <!-- Waves button ripple effects -->
    <script src="{% static 'blog/vendors/Waves/dist/waves.min.js' %}"></script>

    <!-- Autosize - Auto height textarea -->
    <script src="{% static 'blog/vendors/autosize/dist/autosize.min.js' %}"></script>

    <!-- rateYo - Ratings -->
    <script src="{% static 'blog/vendors/src/jquery.rateyo.js' %}"></script>

    <!-- jsSocials - Social link sharing -->
    <script src="{% static 'blog/vendors/jssocials/dist/jssocials.min.js' %}"></script>

    <!-- IE9 Placeholder -->
    <!--[if IE 9 ]>
    <script src="{% static 'blog/vendors/jquery-placeholder/jquery.placeholder.min.js' %}"></script>
    <![endif]-->

    <script src="{% static 'editormd/lib/marked.min.js' %}"></script>
    <script src="{% static 'editormd/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editormd/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editormd/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editormd/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editormd/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editormd/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editormd/editormd.js' %}"></script>
    <script type="text/javascript">
        function AddComment() {
            var body = $('#CommentBody').val();
            $.ajax({
                type: "POST",
                url: "{% url 'blog:comment' %}",
                data: {
                    url: '{{ article.url }}',
                    body: body,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function (data) {
                    if (data != '') {
                        window.location = "{% url 'login' %}"
                    }
                    window.location.reload();
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert(jqXHR, textStatus, errorThrown);
                }
            });
        }
        function ShowReply(ID) {
            $('#ReplyCommentTips').text(values = '回复评论');
            var ReplyComment = $('#ReplyComment');
            ReplyComment.text(values = '添加回复');
            window.location.href = '#blog-comment';
            ReplyComment.unbind();
            ReplyComment.bind('click', function () {
                var body = $('#CommentBody').val();
                $.ajax({
                    type: "POST",
                    url: "{% url 'blog:reply' %}",
                    data: {
                        url: '{{ article.url }}',
                        body: body,
                        commentid: ID,
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function (data) {
                        if (data != '') {
                            window.location = "{% url 'login' %}"
                        }
                        window.location.reload();
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert(jqXHR, textStatus, errorThrown);
                    }
                });
            });
        }
        $(function () {
            var testEditormdView2;
            testEditormdView2 = editormd.markdownToHTML("test-editormd-view2", {
                htmlDecode: "style,script,iframe",
                markdownSourceCode: true,
                emoji: true,
                taskList: true,
                tex: true,
                flowChart: true,
                sequenceDiagram: true
            });
            $('#ReplyComment').bind('click', AddComment);
        });

    </script>
{% endblock %}