July/urls.py
from django.conf.urls import url, include
from users.views import RegisterView, LoginView, LogoutView, PasswordView, RestPasswordView
from blog.views import *

from blog.feeds import RssSiteNewsFeed, AtomSiteNewsFeed
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import BlogSitemap

sitemaps = {
    'static': BlogSitemap,
}

urlpatterns = [
    # ========== Blog Home =========
    url(r'^$', ArticleListView.as_view(), name='index'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^article/(?P<article_url>.*)$', ArticleDetailView.as_view(), name='article'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # ========== User =========
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^password/$', PasswordView.as_view(), name='password'),
    url(r'^rest_password/$', RestPasswordView.as_view(), name='restpassword'),
    # ========== Admin =========
    url(r'^admin/', include('admin.urls', namespace='admin')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^rss\.xml$', RssSiteNewsFeed()),
    url(r'^atom\.xml$', AtomSiteNewsFeed()),
]

apps/admin/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from .views import *

urlpatterns = [
    url(r'^tag/$', TagView.as_view(), name='tag'),
    url(r'^link/$', LinkView.as_view(), name='link'),
    url(r'^users/$', UsersView.as_view(), name='users'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^setting/$', SettingView.as_view(), name='setting'),
    url(r'^upload/$', csrf_exempt(UploadView.as_view()), name='upload'),
    url(r'^categories/$', CategoriesView.as_view(), name='categories'),
    url(r'^article/add/$', ArticleAddView.as_view(), name='article-add'),
    url(r'^article/list/$', ArticleListView.as_view(), name='article-list'),
    url(r'^article/edit/$', ArticleEditView.as_view(), name='article-edit'),
    url(r'^article/body/$', ArticleBodyView.as_view(), name='article-body'),
    url(r'^message/os/$', MessageOSView.as_view(), name='message-os'),
    url(r'^message/comment/$', MessageCommentView.as_view(), name='message-comment'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from utils.default_model import random_nick_name
from blog.models import Article

__all__ = [
    'UserProfile',
    'EmailVerifyCode',
    'Message',
    'Comment',
    'Reply'
]


# Create your models here.

class UserProfile(AbstractUser):
    gender_choices = (
        ('male', '男'),
        ('female', '女'),
        ('unknown', '未知')
    )
    nick_name = models.CharField(max_length=100, default=random_nick_name)
    gender = models.CharField(choices=gender_choices, default='unknown', max_length=20)
    image = models.ImageField(upload_to='avatar/%Y/%m', max_length=100, default='avatar/avatar.png')

    def get_message_count(self):
        return Message.objects.filter(status=False).count()

    def get_comment_count(self):
        return Comment.objects.filter(status=False).count()


class EmailVerifyCode(models.Model):
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=50)
    send_time = models.DateTimeField(auto_now_add=True)


class Message(models.Model):
    add_time = models.DateTimeField(auto_now_add=True)
    body = models.CharField(max_length=200)
    status = models.BooleanField(default=False)


class Comment(models.Model):
    user = models.ForeignKey(UserProfile)
    article = models.ForeignKey(Article, related_name='article_comment')
    body = models.TextField()
    add_time = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def get_reply(self):
        return Reply.objects.filter(comment=self.pk)


class Reply(models.Model):
    user = models.ForeignKey(UserProfile)
    comment = models.ForeignKey(Comment)
    body = models.TextField()
    add_time = models.DateTimeField(auto_now_add=True)

apps/users/forms.py
from django import forms

__all__ = [
    'RegisterForm',
    'LoginForm',
    'RestPasswordForm',
    'AdminRestPasswordForm'
]


class RegisterForm(forms.Form):
    """注册Form验证"""
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    retype_password = forms.CharField(required=True, min_length=5)
    """验证两个密码是否一致"""


class LoginForm(forms.Form):
    """登录Form验证"""
    email = forms.CharField(required=True, max_length=150)  # 字符串类型，必填字段，最大长度150
    password = forms.CharField(required=True, max_length=128)  # 字符串类型，必填字段，最大长度128


class RestPasswordForm(forms.Form):
    code = forms.CharField()
    password = forms.CharField(required=True, min_length=5)
    retype_password = forms.CharField(required=True, min_length=5)


class AdminRestPasswordForm(forms.Form):
    oldpassword = forms.CharField(required=True, )
    newpassword = forms.CharField(required=True, min_length=5)
    retypepassword = forms.CharField(required=True, min_length=5)

apps/users/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.hashers import make_password
from django.contrib.auth.backends import ModelBackend
from users.models import Message, EmailVerifyCode
from utils.email_send import send_password_email
from django.views.generic import View
from django.utils import timezone
from .models import UserProfile
from django.db.models import Q
from .forms import *
from utils.mixin_utils import LoginRequiredMixin

__all__ = [
    'RegisterView',
    'LoginView',
    'LogoutView',
    'PasswordView'
]


class CustomBackend(ModelBackend):
    """自定义auth验证，可以通过用户名邮箱登录"""

    def authenticate(self, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username) | Q(email=username))  # 通过用户名或邮箱获取用户是否存在
            if user.check_password(password):  # 如果用户密码正确返回user对象
                return user
            else:  # 出错或者用户密码错误就返回None
                return None
        except Exception:
            return None


# Create your views here.

class RegisterView(View):
    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        register_form = RegisterForm(request.POST)  # 验证传过来的参数
        if register_form.is_valid():
            email = request.POST.get('email', '')  # 获取邮箱
            try:
                UserProfile.objects.get(email=email)  # 如果邮箱已经存在
                return render(request, 'register.html', {'errors': '邮箱：%s 已存在！' % email})
            except ObjectDoesNotExist:
                password = request.POST.get('password', '')  # 获取密码
                retype_password = request.POST.get('retype_password', '')  # 确认密码
                if password == retype_password:
                    UserProfile.objects.create(username=email, email=email, password=make_password(password))
                    Message.objects.create(body="用户%s于%s进行了注册" % (email, timezone.now()))
                    return HttpResponseRedirect(reverse('login'))  # 跳转到登录页面
                else:
                    errors = '两次密码不一致~'
                    return render(request, 'register.html', {'errors': errors})
        else:
            return render(request, 'register.html', {'errors': register_form.errors})


class LoginView(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        """验证用户是否是否可以成功登录"""
        login_form = LoginForm(request.POST)  # FORM验证传过来的值是否合法
        if login_form.is_valid():  # 验证是否错误
            email = request.POST.get('email', '')  # 获取用户名
            password = request.POST.get('password', '')  # 获取密码
            user = authenticate(username=email, password=password)  # 验证用户名和密码
            if user is not None:  # 如果用户名和密码匹配
                if user.is_active:  # 如果用户是激活状态
                    login(request, user)  # 把SESSION和COOKIE写入request
                    if user.is_superuser:
                        return HttpResponseRedirect(reverse('admin:dashboard'))  # 返回首页
                    else:
                        return HttpResponseRedirect(reverse('index'))  # 返回首页
                else:  # 用户未激活
                    return render(request, 'login.html', {'errors': '用户尚未激活！'})
            else:  # 用户名和密码错误
                return render(request, 'login.html', {'errors': '用户名或密码错误！'})
        else:  # FORM验证出错，并吧出错信息传递到前端
            return render(request, 'login.html', {'errors': login_form.errors})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('login'))


class PasswordView(View):
    def get(self, request):
        code = request.GET.get('code', '')
        if code:
            try:
                EmailVerifyCode.objects.get(code=code)
                return render(request, 'password.html', {'code': code, 'flag': True})
            except EmailVerifyCode.DoesNotExist:
                return HttpResponse('重置密码链接已失效~')
        else:
            return render(request, 'password.html')

    def post(self, request):
        email = request.POST.get('email', '')
        try:
            UserProfile.objects.get(email=email)
            result = send_password_email(email=email)
            if result:
                return HttpResponse('重置密码的链接已发送至你的邮箱，请注意查收~')
            return HttpResponse('用户不存在~')
        except UserProfile.DoesNotExist:
            return HttpResponse('用户不存在~')


class RestPasswordView(View):
    def post(self, request):
        code = request.POST.get('code')  # Code
        if code:
            rest_form = RestPasswordForm(request.POST)
            if rest_form.is_valid():
                password = request.POST.get('password', '')  # 获取密码
                retype_password = request.POST.get('retype_password', '')  # 确认密码
                if password == retype_password:
                    emailverify = EmailVerifyCode.objects.get(code=code)
                    email = emailverify.email
                    user = UserProfile.objects.get(email=email)
                    user.password = make_password(password)
                    user.save()
                    emailverify.delete()
                    Message.objects.create(body="用户%s于%s修改了密码" % (email, timezone.now()))
                    return HttpResponseRedirect(reverse('login'))
                else:
                    return HttpResponse('两次密码不一致~')
            else:
                return HttpResponse(rest_form.errors)
        else:
            admin_password_form = AdminRestPasswordForm(request.POST)
            if admin_password_form.is_valid():
                oldpassword = request.POST.get('oldpassword')
                newpassword = request.POST.get('newpassword')
                retypepassword = request.POST.get('retypepassword')
                user = authenticate(username=request.user.email, password=oldpassword)
                if newpassword == retypepassword and user:
                    user.password = make_password(newpassword)
                    user.save()
                    logout(request)
                    Message.objects.create(body="用户%s于%s通过后台修改了密码" % (request.user.email, timezone.now()))
                    return HttpResponseRedirect(reverse('login'))
                else:
                    return HttpResponse('请确保两次密码相同且旧密码正确~')
            else:
                return HttpResponse(admin_password_form.errors)

apps/admin/templates/article-edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}安生 | 编辑文章{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'editormd/css/editormd.css' %}"/>
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
{% endblock %}

{% block content-wrapper %}
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                编辑文章
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url 'admin:dashboard' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                <li><a>文章管理</a></li>
                <li class="active">编辑文章</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <form action="{% url 'admin:article-add' %}" method="post">
                    {% csrf_token %}
                    <div class="box">
                        <div class="box-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <input class="form-control input-lg" type="text" name="title" placeholder="文章标题" value="{{ article.title }}">
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-xs-1">
                                    <div class="form-group">
                                        <select class="form-control" name="status">
                                            {% if article.status == '0' %}
                                                <option value="0">发布</option>
                                                <option value="1">存稿</option>
                                            {% elif article.status == '1' %}
                                                <option value="1">存稿</option>
                                                <option value="0">发布</option>
                                            {% endif %}
                                        </select>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <input type="text" class="form-control" name="url" placeholder="URL" value="{{ article.url }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <select class="form-control select2" multiple="multiple" data-placeholder="分类" style="width: 100%;" name="categories">
                                            {% for category in categories %}
                                                <option value="{{ category.name }}">{{ category.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <select class="form-control select2" multiple="multiple" data-placeholder="标签" style="width: 100%;" name="tags">
                                            {% for tag in tags %}
                                                <option value="{{ tag.name }}">{{ tag.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>已关联的分类</label>
                                        <input class="form-control" type="text" value="{{ exist_categories }}" name="exist_categories">
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>已关联的标签</label>
                                        <input class="form-control" type="text" value="{{ exist_tag }}" name="exist_tag">
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div id="layout">
                            <div id="editormd"></div>
                        </div>
                    </div>
                    <div class="box-footer" style="background-color: #ecf0f5">
                        <button type="submit" class="btn btn-primary pull-right btn-lg">保存</button>
                    </div>
                    <input style="display: none" type="text" name="id" value="{{ article.id }}">
                </form>
            </div>
        </section>
    </div>

{% endblock %}

{% block custom_js %}
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
    <script src="{% static 'editormd/editormd.js' %}"></script>
    <script type="text/javascript">
        var Editor;
        $(function () {
            $.get('{% url 'admin:article-body' %}?aid={{ article.id }}', function (md) {
                Editor = editormd("editormd", {
                    width: "100%",
                    height: 740,
                    path: '../lib/',
                    markdown: md,
                    codeFold: true,
                    saveHTMLToTextarea: true,
                    searchReplace: true,
                    htmlDecode: "style,script,iframe|on*",
                    emoji: true,
                    taskList: true,
                    tocm: true,
                    tex: true,
                    flowChart: true,
                    sequenceDiagram: true,
                    imageUpload: true,
                    imageFormats: ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                    imageUploadURL: "/admin/upload/"
                });
            });
            $(".select2").select2();
        });
    </script>
{% endblock %}

apps/admin/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>

    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link href="//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Ionicons -->
    <link href="//cdn.bootcss.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
    {% block custom_css %}

    {% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <!-- Logo -->
        <a href="{% url 'admin:dashboard' %}" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>A</b>S</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>An</b>Sheng</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">切换导航</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->
                    {% if request.user.is_superuser %}
                        <li class="dropdown messages-menu">
                            <a href="{% url 'admin:message-comment' %}">
                                <i class="fa fa-envelope-o"></i>
                                <span class="label label-success">{{ request.user.get_comment_count }}</span>
                            </a>
                        </li>


                        <!-- Notifications: style can be found in dropdown.less -->
                        <li class="dropdown notifications-menu">
                            <a href="{% url 'admin:message-os' %}">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-warning">{{ request.user.get_message_count }}</span>
                            </a>
                        </li>
                    {% endif %}

                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{ MEDIA_URL }}{{ request.user.image }}" class="user-image" alt="User Image">
                            <span class="hidden-xs">{{ request.user.nick_name }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{{ MEDIA_URL }}{{ request.user.image }}" class="img-circle" alt="User Image">
                                <p>
                                    {{ request.user.email }}
                                    <small>注册日期：{{ request.user.date_joined }}</small>
                                </p>
                            </li>

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{% url 'admin:profile' %}" class="btn btn-default btn-flat">简介</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'logout' %}" class="btn btn-default btn-flat">登出</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>

        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{{ MEDIA_URL }}{{ request.user.image }}" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>{{ request.user.nick_name }}</p>
                    <a><i class="fa fa-circle text-success"></i> 在线</a>
                </div>
            </div>

            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu">
                <li class="header">主导航</li>
                <li class="{% if request.path == '/admin/' %}active{% endif %} treeview">
                    <a href="{% url 'admin:dashboard' %}">
                        <i class="fa fa-dashboard"></i> <span>仪表盘</span>
                    </a>
                </li>
                {% if request.user.is_superuser %}
                    <li class="treeview {% if request.path|slice:'14' == '/admin/article' %}active{% endif %}">
                        <a href="#">
                            <i class="fa fa-align-justify"></i> <span>文章管理</span>
                            <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                        </a>
                        <ul class="treeview-menu">
                            <li {% if request.path == '/admin/article/add/' %}class="active"{% endif %}><a href="{% url 'admin:article-add' %}"><i class="fa fa-circle-o"></i> 添加文章</a></li>
                            <li {% if request.path == '/admin/article/list/' %}class="active"{% endif %}><a href="{% url 'admin:article-list' %}"><i class="fa fa-circle-o"></i> 文章列表</a></li>

                        </ul>
                    </li>
                    <li class="treeview {% if request.path|slice:'10' == '/admin/tag' %}active{% elif request.path|slice:'17' == '/admin/categories' %}active{% endif %}">
                        <a href="#">
                            <i class="fa fa-map-pin"></i> <span>标签/分类</span>
                            <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                        </a>
                        <ul class="treeview-menu">
                            <li {% if request.path == '/admin/tag/' %}class="active"{% endif %}><a href="{% url 'admin:tag' %}"><i class="fa fa-circle-o"></i> 标签列表</a></li>
                            <li {% if request.path == '/admin/categories/' %}class="active"{% endif %}><a href="{% url 'admin:categories' %}"><i class="fa fa-circle-o"></i> 分类列表</a></li>
                        </ul>
                    </li>

                    <li class="treeview {% if request.path|slice:'14' == '/admin/message' %}active{% endif %}">
                        <a href="#">
                            <i class="fa fa-envelope"></i> <span>消息管理</span>

                            <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                                <small class="label pull-right bg-yellow">{{ request.user.get_message_count }}</small>
                            <small class="label pull-right bg-green">{{ request.user.get_comment_count }}</small>
                        </span>
                        </a>

                        <ul class="treeview-menu">
                            <li {% if request.path == '/admin/message/comment/' %}class="active"{% endif %}><a href="{% url 'admin:message-comment' %}"><i class="fa fa-circle-o"></i> 评论消息</a></li>
                            {% if request.user.is_superuser %}
                                <li {% if request.path == '/admin/message/os/' %}class="active"{% endif %}><a href="{% url 'admin:message-os' %}"><i class="fa fa-circle-o"></i> 系统消息</a></li>
                            {% endif %}
                        </ul>
                    </li>
                {% endif %}
                <li class="header">系统配置</li>
                {% if request.user.is_superuser %}
                    <li class="{% if request.path == '/admin/users/' %}active{% endif %}">
                        <a href="{% url 'admin:users' %}">
                            <i class="fa fa-circle-o"></i> <span>用户列表</span>
                        </a>
                    </li>
                    <li {% if request.path == '/admin/link/' %}class="active"{% endif %}><a href="{% url 'admin:link' %}"><i class="fa fa-circle-o text-aqua"></i> <span>友情链接</span></a></li>
                {% endif %}
                <li {% if request.path == '/admin/profile/' %}class="active"{% endif %}><a href="{% url 'admin:profile' %}"><i class="fa fa-circle-o text-red"></i> <span>个人信息</span></a></li>
                {% if request.user.is_superuser %}
                    <li {% if request.path == '/admin/setting/' %}class="active"{% endif %}><a href="{% url 'admin:setting' %}"><i class="fa fa-circle-o text-yellow"></i> <span>全局设置</span></a></li>
                {% endif %}
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    {% block content-wrapper %}

    {% endblock %}

    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 0.2.0
        </div>
        <strong>Copyright &copy; 2017-2017 <a href="https://www.ansheng.me">安生</a>.</strong> All rights
        reserved.
    </footer>

</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/app.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparkline/jquery.sparkline.min.js' %}"></script>
<!-- SlimScroll 1.3.0 -->
<script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
{% block custom_js %}

{% endblock %}
</body>
</html>

apps/admin/templates/dashboard.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}安生 | 仪表板{% endblock %}
{% block content-wrapper %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>仪表盘</h1>
            <ol class="breadcrumb">
                <li><a href="{% url 'admin:dashboard' %}"><i class="fa fa-dashboard"></i> 首页</a></li>
                <li class="active">仪表盘</li>
            </ol>
        </section>
        <!-- Main content -->
        <section class="content">
            <!-- Info boxes -->
            <h1>Hi, {{ request.user.nick_name }}</h1>
            <h2>我确实不知道写点什么了~</h2>
            <h3>如果你知道，你可以对本页进行编辑~</h3>
            <h4>本系统源代码：<a href="https://github.com/anshengme/july" target="_blank">https://github.com/anshengme/july</a></h4>
            <h5>当然她是完全开源的，遵守MIT协议，你可以自定义修改，二次开发，完全把她当做自己的~</h5>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
{% endblock %}